# Generated by Django 5.0.4 on 2024-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Marka əlavə olunmalıdır!', max_length=50, verbose_name='Marka')),
                ('model', models.CharField(help_text='Model əlavə olunmalıdır!', max_length=50, verbose_name='Model')),
                ('imei', models.CharField(help_text='İmei əlavə olunmalıdır', max_length=15, unique=True, verbose_name='IMEI')),
                ('note', models.TextField(blank=True, help_text='Vacib deyil!', null=True, verbose_name='Əlavə məlumat')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Daxili olma tarixi')),
                ('status', models.CharField(choices=[('Qeydiyyatdan keçirilməyib!', 'Qeydiyyatdan keçirilməyib!'), ('Qeydiyyatdan keçib!', 'Qeydiyyatdan keçib!')], default='Qeydiyyatdan keçirilməyib!', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefonlar',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maksimum 50 simvol', max_length=50, verbose_name='Adı')),
                ('email', models.EmailField(help_text='Boş saxlanıla bilməz', max_length=254, verbose_name='Elektron poçt')),
            ],
            options={
                'verbose_name': 'Elektron poçt alıcısı',
                'verbose_name_plural': 'Elektron poçt alıcıları',
            },
        ),
    ]
